import type { PatientDetailDto, PatientFields, UpdatePatientInput } from "@/api/patients";

/** Defaults for every field — used to seed the minimal create dialog. */
export function emptyPatientFields(): PatientFields {
  return {
    patientCode: "",
    isActive: true,
    firstName: "",
    lastName: "",
    middleInitial: null,
    dateOfBirth: "",
    gender: "",
    maritalStatus: null,
    isMinor: false,
    raceId: null,
    ethnicityId: null,
    languageId: null,
    smokingStatusId: null,
    smokingStartDate: null,
    smokingEndDate: null,
    medicalAlertNotes: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    phone: null,
    phoneExtension: null,
    cellPhone: null,
    email: null,
    preferredContactMethodId: null,
    ssn: null,
    guardianSsn: null,
    occupation: null,
    employerName: null,
    employerAddress1: null,
    employerAddress2: null,
    employerCity: null,
    employerState: null,
    employerZipCode: null,
    employerPhone: null,
    employerPhoneExtension: null,
    guardianFirstName: null,
    guardianLastName: null,
    guardianMiddleInitial: null,
    guardianDateOfBirth: null,
    guardianGender: null,
    guardianMaritalStatus: null,
    guardianAddress1: null,
    guardianAddress2: null,
    guardianCity: null,
    guardianState: null,
    guardianZipCode: null,
    guardianPhone: null,
    guardianCellPhone: null,
    guardianEmployerName: null,
    guardianEmployerAddress1: null,
    guardianEmployerAddress2: null,
    guardianEmployerCity: null,
    guardianEmployerState: null,
    guardianEmployerZipCode: null,
    nextOfKinFirstName: null,
    nextOfKinLastName: null,
    nextOfKinPhone: null,
    nextOfKinRelation: null,
    nextOfKinRelationRoleCode: null,
    referralTypeId: null,
    hasNoKnownProblems: false,
    hasNoKnownMedications: false,
    hasNoKnownAllergies: false,
    receivesEmailReminders: false,
    lastVisitDate: null,
    nextVisitDate: null,
  };
}

/**
 * Flattens a `PatientDetailDto` back into `PatientFields` — the inverse of
 * the backend's nested DTO shaping. `ssn`/`guardianSsn` are intentionally
 * left `null`: the API never returns plaintext PHI (only `phi.ssnMasked`),
 * and `UpdatePatientCommandHandler` treats a blank SSN as "leave unchanged"
 * (see its comment), so omitting it here is correct for every section's
 * edit dialog except PHI's own, which sets a real value when the user
 * enters one.
 */
export function detailToFields(detail: PatientDetailDto): PatientFields {
  const { demographics, contact, employment, guardian, nextOfKin } = detail;
  return {
    patientCode: detail.patientCode,
    isActive: detail.isActive,
    firstName: demographics.firstName,
    lastName: demographics.lastName,
    middleInitial: demographics.middleInitial ?? null,
    dateOfBirth: demographics.dateOfBirth,
    gender: demographics.gender,
    maritalStatus: demographics.maritalStatus ?? null,
    isMinor: demographics.isMinor,
    raceId: demographics.raceId ?? null,
    ethnicityId: demographics.ethnicityId ?? null,
    languageId: demographics.languageId ?? null,
    smokingStatusId: demographics.smokingStatusId ?? null,
    smokingStartDate: demographics.smokingStartDate ?? null,
    smokingEndDate: demographics.smokingEndDate ?? null,
    medicalAlertNotes: demographics.medicalAlertNotes ?? null,
    address1: contact.address1 ?? null,
    address2: contact.address2 ?? null,
    city: contact.city ?? null,
    state: contact.state ?? null,
    zipCode: contact.zipCode ?? null,
    phone: contact.phone ?? null,
    phoneExtension: contact.phoneExtension ?? null,
    cellPhone: contact.cellPhone ?? null,
    email: contact.email ?? null,
    preferredContactMethodId: contact.preferredContactMethodId ?? null,
    ssn: null,
    guardianSsn: null,
    occupation: employment?.occupation ?? null,
    employerName: employment?.employerName ?? null,
    employerAddress1: employment?.employerAddress1 ?? null,
    employerAddress2: employment?.employerAddress2 ?? null,
    employerCity: employment?.employerCity ?? null,
    employerState: employment?.employerState ?? null,
    employerZipCode: employment?.employerZipCode ?? null,
    employerPhone: employment?.employerPhone ?? null,
    employerPhoneExtension: employment?.employerPhoneExtension ?? null,
    guardianFirstName: guardian?.firstName ?? null,
    guardianLastName: guardian?.lastName ?? null,
    guardianMiddleInitial: guardian?.middleInitial ?? null,
    guardianDateOfBirth: guardian?.dateOfBirth ?? null,
    guardianGender: guardian?.gender ?? null,
    guardianMaritalStatus: guardian?.maritalStatus ?? null,
    guardianAddress1: guardian?.address1 ?? null,
    guardianAddress2: guardian?.address2 ?? null,
    guardianCity: guardian?.city ?? null,
    guardianState: guardian?.state ?? null,
    guardianZipCode: guardian?.zipCode ?? null,
    guardianPhone: guardian?.phone ?? null,
    guardianCellPhone: guardian?.cellPhone ?? null,
    guardianEmployerName: guardian?.employerName ?? null,
    guardianEmployerAddress1: guardian?.employerAddress1 ?? null,
    guardianEmployerAddress2: guardian?.employerAddress2 ?? null,
    guardianEmployerCity: guardian?.employerCity ?? null,
    guardianEmployerState: guardian?.employerState ?? null,
    guardianEmployerZipCode: guardian?.employerZipCode ?? null,
    nextOfKinFirstName: nextOfKin?.firstName ?? null,
    nextOfKinLastName: nextOfKin?.lastName ?? null,
    nextOfKinPhone: nextOfKin?.phone ?? null,
    nextOfKinRelation: nextOfKin?.relation ?? null,
    nextOfKinRelationRoleCode: nextOfKin?.relationRoleCode ?? null,
    referralTypeId: detail.referralTypeId ?? null,
    hasNoKnownProblems: detail.hasNoKnownProblems,
    hasNoKnownMedications: detail.hasNoKnownMedications,
    hasNoKnownAllergies: detail.hasNoKnownAllergies,
    receivesEmailReminders: detail.receivesEmailReminders,
    lastVisitDate: detail.lastVisitDate ?? null,
    nextVisitDate: detail.nextVisitDate ?? null,
  };
}

/**
 * Merges a section's edits on top of the patient's current full field set
 * into a ready-to-send `UpdatePatientInput`. `UpdatePatientCommand` is a
 * full-replace PUT (no partial-update endpoint), so every section's save
 * must resend every other section's untouched values, not just its own.
 */
export function mergePatientUpdate(
  detail: PatientDetailDto,
  overrides: Partial<PatientFields>,
): UpdatePatientInput {
  return { ...detailToFields(detail), ...overrides, patientId: detail.id };
}
