// <auto-generated />
using System;
using FSH.Modules.Patient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.Migrations.PostgreSQL.Patient
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20260625130241_AddPatientIncidents")]
    partial class AddPatientIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patient")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Patient.Domain.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasNoKnownAllergies")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNoKnownMedications")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNoKnownProblems")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("date");

                    b.Property<long?>("LegacyUniqueId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NextVisitDate")
                        .HasColumnType("date");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ReceivesEmailReminders")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LegacyUniqueId");

                    b.HasIndex("PatientCode", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_PatientCode")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Patients", "patient");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Patient.Domain.PatientIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccidentState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("AccidentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("AdherenceToPlan")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfInitialVisit")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOfLoss")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAccident")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SummaryOfCare")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "IsClosed");

                    b.HasIndex("PatientId", "IsDeleted");

                    b.ToTable("PatientIncidents", "patient");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Patient.Domain.PatientIncidentDiagnostic", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentId", "DiagnosticId");

                    b.ToTable("PatientIncidentDiagnostics", "patient");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Patient.Domain.Patient", b =>
                {
                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address2");

                            b1.Property<string>("CellPhone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CellPhone");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Email")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Phone");

                            b1.Property<string>("PhoneExtension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PhoneExtension");

                            b1.Property<int?>("PreferredContactMethodId")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("State");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientDemographics", "Demographics", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<int?>("EthnicityId")
                                .HasColumnType("integer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Gender");

                            b1.Property<bool>("IsMinor")
                                .HasColumnType("boolean");

                            b1.Property<int?>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MaritalStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("MaritalStatus");

                            b1.Property<string>("MedicalAlertNotes")
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("MedicalAlertNotes");

                            b1.Property<string>("MiddleInitial")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("MiddleInitial");

                            b1.Property<int?>("RaceId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("SmokingEndDate")
                                .HasColumnType("date");

                            b1.Property<DateTime?>("SmokingStartDate")
                                .HasColumnType("date");

                            b1.Property<int?>("SmokingStatusId")
                                .HasColumnType("integer");

                            b1.HasKey("PatientId");

                            b1.HasIndex("LastName");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientEmployment", "Employment", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EmployerAddress1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EmployerAddress1");

                            b1.Property<string>("EmployerAddress2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EmployerAddress2");

                            b1.Property<string>("EmployerCity")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("EmployerCity");

                            b1.Property<string>("EmployerName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EmployerName");

                            b1.Property<string>("EmployerPhone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("EmployerPhone");

                            b1.Property<string>("EmployerPhoneExtension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EmployerPhoneExtension");

                            b1.Property<string>("EmployerState")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("EmployerState");

                            b1.Property<string>("EmployerZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EmployerZipCode");

                            b1.Property<string>("Occupation")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Occupation");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientGuardian", "Guardian", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GuardianAddress1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GuardianAddress2");

                            b1.Property<string>("CellPhone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("GuardianCellPhone");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GuardianCity");

                            b1.Property<DateTime?>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("EmployerAddress1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GuardianEmployerAddress1");

                            b1.Property<string>("EmployerAddress2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GuardianEmployerAddress2");

                            b1.Property<string>("EmployerCity")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GuardianEmployerCity");

                            b1.Property<string>("EmployerName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GuardianEmployerName");

                            b1.Property<string>("EmployerState")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("GuardianEmployerState");

                            b1.Property<string>("EmployerZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("GuardianEmployerZipCode");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GuardianFirstName");

                            b1.Property<string>("Gender")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("GuardianGender");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GuardianLastName");

                            b1.Property<string>("MaritalStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("GuardianMaritalStatus");

                            b1.Property<string>("MiddleInitial")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("GuardianMiddleInitial");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("GuardianPhone");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("GuardianState");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("GuardianZipCode");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientInsurance", "Insurance", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("InsuredDateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("InsuredEmployerName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("InsuredEmployerName");

                            b1.Property<string>("InsuredFullName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("InsuredFullName");

                            b1.Property<int?>("ReferralTypeId")
                                .HasColumnType("integer");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientNextOfKin", "NextOfKin", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("NextOfKinFirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("NextOfKinLastName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("NextOfKinPhone");

                            b1.Property<string>("Relation")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("NextOfKinRelation");

                            b1.Property<string>("RelationRoleCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("NextOfKinRelationRoleCode");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("FSH.Modules.Patient.Domain.PatientPhi", "PHI", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GuardianSsn")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("GuardianSsnEncrypted");

                            b1.Property<string>("Ssn")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("SsnEncrypted");

                            b1.Property<string>("SsnSearchHash")
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("SsnSearchHash")
                                .IsFixedLength();

                            b1.HasKey("PatientId");

                            b1.HasIndex("SsnSearchHash");

                            b1.ToTable("Patients", "patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Demographics")
                        .IsRequired();

                    b.Navigation("Employment");

                    b.Navigation("Guardian");

                    b.Navigation("Insurance");

                    b.Navigation("NextOfKin");

                    b.Navigation("PHI")
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Patient.Domain.PatientIncidentDiagnostic", b =>
                {
                    b.HasOne("FSH.Modules.Patient.Domain.PatientIncident", null)
                        .WithMany("Diagnostics")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Patient.Domain.PatientIncident", b =>
                {
                    b.Navigation("Diagnostics");
                });
#pragma warning restore 612, 618
        }
    }
}
