import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Copy, Lock } from "lucide-react";
import { toast } from "sonner";
import { exportReportsPdf, type ExportedReportPdf } from "@/api/reports";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Field } from "@/components/list";
import { describe } from "@/lib/list-helpers";

/** Mirrors the backend's ExportPatientReportsPdfQueryValidator. */
const MIN_PASSWORD_LENGTH = 8;

type Props = {
  reportId: string;
  open: boolean;
  onClose(): void;
};

/**
 * Protected print (BackChart's padlock button next to Export PDF): downloads the report as an
 * AES-256 encrypted PDF that opens only with the password entered here. The password is sent with
 * the one request and never stored, so the dialog is also the only place the user will ever see it
 * — delivering it to the recipient out of band is on them, and the copy below says so.
 */
export function ProtectedPrintDialog({ reportId, open, onClose }: Props) {
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [exported, setExported] = useState<ExportedReportPdf | null>(null);

  const tooShort = password.length > 0 && password.length < MIN_PASSWORD_LENGTH;
  const mismatch = confirmPassword.length > 0 && password !== confirmPassword;
  const canDownload =
    password.length >= MIN_PASSWORD_LENGTH && password === confirmPassword;

  const downloadMutation = useMutation({
    mutationFn: () => exportReportsPdf([reportId], password),
    onSuccess: (file) => {
      setExported(file);
      toast.success("Protected PDF downloaded.");
    },
    onError: (err) =>
      toast.error("Failed to export the protected PDF.", { description: describe(err) }),
  });

  const copySha = async (sha: string) => {
    try {
      await navigator.clipboard.writeText(sha);
      toast.info("SHA256SUM copied to clipboard.");
    } catch {
      toast.warning("Could not copy to clipboard.");
    }
  };

  const reset = () => {
    setPassword("");
    setConfirmPassword("");
    setExported(null);
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) {
          reset();
          onClose();
        }
      }}
    >
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Protected Print</DialogTitle>
        </DialogHeader>

        <DialogBody className="space-y-4">
          <p className="rounded-lg border border-[var(--color-border)] bg-[var(--color-accent)] px-3 py-2 text-[12px] text-[var(--color-muted-foreground)]">
            The PDF is encrypted and will only open with the password you set here. We never store
            it — send it to the recipient separately from the file itself.
          </p>

          <Field id="pp-password" label="Password" required>
            <Input
              id="pp-password"
              type="password"
              autoComplete="new-password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder={`At least ${MIN_PASSWORD_LENGTH} characters`}
            />
          </Field>
          {tooShort && (
            <p className="text-[12px] text-[var(--color-destructive)]">
              Use at least {MIN_PASSWORD_LENGTH} characters.
            </p>
          )}

          <Field id="pp-confirm" label="Confirm password" required>
            <Input
              id="pp-confirm"
              type="password"
              autoComplete="new-password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
            />
          </Field>
          {mismatch && (
            <p className="text-[12px] text-[var(--color-destructive)]">
              The two passwords do not match.
            </p>
          )}

          {exported && (
            <div className="space-y-1.5 rounded-lg border border-[var(--color-border)] p-3">
              <p className="text-[12px] font-semibold uppercase tracking-wide text-[var(--color-primary)]">
                Downloaded File
              </p>
              <p className="text-[12px] font-medium">{exported.fileName}</p>
              <p className="text-[12px] text-[var(--color-muted-foreground)]">
                The SHA256SUM verifies the file you downloaded is exactly the file generated by the
                server and was not altered in transit.
              </p>
              <div className="flex items-center gap-1.5">
                <code className="min-w-0 break-all text-[11px] text-[var(--color-muted-foreground)]">
                  {exported.sha256}
                </code>
                <button
                  type="button"
                  title="Copy SHA256SUM to clipboard"
                  aria-label="Copy SHA256SUM to clipboard"
                  onClick={() => void copySha(exported.sha256)}
                  className="inline-flex size-6 shrink-0 items-center justify-center rounded-md border border-[var(--color-border)] transition-colors hover:bg-[var(--color-accent)]"
                >
                  <Copy className="size-3.5" />
                </button>
              </div>
            </div>
          )}
        </DialogBody>

        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="outline">
              Close
            </Button>
          </DialogClose>
          <Button
            type="button"
            disabled={!canDownload || downloadMutation.isPending}
            onClick={() => downloadMutation.mutate()}
          >
            <Lock className="size-4" />
            {downloadMutation.isPending ? "Preparing…" : "Download"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
