<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Administration</RootNamespace>
		<AssemblyName>FSH.Modules.Administration</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
		<ProjectReference Include="..\Modules.Administration.Contracts\Modules.Administration.Contracts.csproj" />
	</ItemGroup>

</Project>
